version: '3.3'

services:
  postgres-lab-idrd-back:
    image: postgres:13
    container_name: postgres-lab-idrd-back
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5433:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  pdadmin-lab-idrd-back:
    image: dpage/pgadmin4
    container_name: pgadmin-lab-idrd-back
    environment:
      PGADMIN_DEFAULT_EMAIL: 'root@admin.com'
      PGADMIN_DEFAULT_PASSWORD: 'admin'
    ports:
      - "5050:80"